<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const p1 = new Promise((resolve, reject) => {
            console.log("开启请求a数据");
            try {
                throw new Error("反正你错了。。。")

                setTimeout(() => {
                    console.log("a数据请求成功");
                    //假设请求的对象是data
                    const data = {
                        name: "laoli"
                    }
                    //返回成功状态，并把data传递出去
                    resolve(data);
                }, 1000)

            } catch (e) {
                console.log("err", e);
                //返回失败，并传递错误信息出去
                reject(e);
            }
        })



        /* 
            then其实可以接受两个回调函数：
                - 第一个回调函数是处理调用then的成功状态的promise对象的回调函数
                - 第二个回调函数是处理调用then的失败状态的promise对象的回调函数（其实就是catch）
        
        
        */

        console.log(p1.then(() => {
                return 1
            }, () => {
                return 2
            })
            .catch(3))

        console.log(p1.then(() => {
            return 1
        }).catch(3))
    </script>
</body>

</html>